name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Cache Library directory
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-${{ runner.os }}-
      - name: Run tests
        id: test
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          coverageOptions: generateHtmlReport;assemblyFilters:-Tests
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.test.outputs.artifactsPath }}
          name: Test results
      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.test.outputs.coveragePath }}
          name: Coverage results
